### ISSUE TITLE
Figure out a deployment strategy

### ISSUE THREAD

**Issue by jgraham** [mjzffr/version-control-tools#4]
We need to work out where we are going to deploy and how we are going to manage deployments. e.g. deploy to AWS, with ansible controlling rollout, and a local docker environment that replicates the deployed setup.

**Comment by mjzffr** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1401644

**Comment by mjzffr** [comment]
For now we have an isolated EC2 instance and we want to use a lot of the same deployment scripts/steps as servosync in version-control-tools.

To run a prototype of wptsync against elm and a fork of wpt on that temporary EC2 instance:

- [x] Configure venv for production
- [x] Configure permissions for wptsync os user, sudo
- [x] Write steps for seeding gecko and wpt repositories
- [x] Start services much as we do with our Docker setup already
- [ ] Get L2 access for wptsync account (Bug 1418492)
- (Deprecated) _We need https://github.com/mozilla-platform-ops/devservices-aws/pull/71 to provision the EC2 instance properly with secrets._

To deploy (production) (with Cloud Services) :

- [x] Complete RRA (Bug 1419058)
- [ ] Land wpt-sync work in version-control-tools (it might make more sense to move to our own github repo?)
- [ ] Get L3 access for wptsync account 
- [x] Possibly move settings out of sync.ini into ansible playbooks.
- [x] Investigate whether we want to run our scripts as several systemd services (like servosync)
- [x] Investigate how to deal with EC2 instance (storage) being blown away at any moment.
- [ ] Produce a Docker image according to https://github.com/mozilla-services/Dockerflow

**Comment by mjzffr** [comment]
Some questions to discuss with mozilla-services:

1. (Prereq) We need an ops person assigned to us to be able to deploy.
2. Under the mozilla-services deployment scheme, will we be able to get ssh access to the EC2 instance to perform manual interventions on the sync process?
3. How is our Docker image actually used in the mozilla-services deployment process? e.g. Can we specify what `docker run` options to use aside from env vars? How do we specify our requirements for the EC2 instance? What's the best way to mimic the deployment scenario in the Cloud Services Dev IAM?
4. Related to specifying our requirements for EC2 instance: we need an EBS volume mounted to the Docker container. Who sets this up? How should we configure where it's mounted?
5. How should we package + provide credentials? (pulse, ssh, bz api key, etc.) Is providing a config file acceptable?
6. Does the requirement for `/__version__`, `/__heartbeat__` endpoints apply to our use case? (see https://github.com/mozilla-services/Dockerflow/blob/master/README.md#containerized-app-requirements)

**Comment by mjzffr** [comment]
Brain dump of meeting at Austin with Travis Blow, ckolos, hwine and....

* Main contact person for us: ckolos
* Cloud Ops is not going to deploy or monitor for us. They will set up infra and we deploy. If EC2 instance is down we file bug/issue with cloud ops and they can respond within a couple of days.
* 2nd or 3rd week of January we should have ssh access to a box where we can manually deploy. We need to specify size of EC2 instance, capacity of EBS volume (or if we want to use EFS) and they'll set that up. Most likely Centos 7 box. 
* Will provide jgraham and maja_zf access to bastion. DUO auth app for VPN access so can ssh into host.
* hg credentials have to be set up by another group (gps et al), so that's on a different timeline. Check with hwine. Credentials will be generated/stored directly on host. If host goes down, regenerate?
* Otherwise, it's up to us to manage/store all other credentials (github, bugzilla).
* (todo) Check out monitoring options on dev IAM account (AWS), or I think ckolos said they could set up very basic monitoring for us (email to mailing list in case host is down)
* EBS versus EFS: EBS is faster but if host goes down, can be left in inconsistent state. EFS is ubiquitous; easier to provide access to it from more hosts (?). Used for phabricator.
